### ISSUE TITLE
about the detailed running instructions and orchestration scripts

### ISSUE THREAD

**Issue by Cyich** [wanmok/joint-arglinking#1]
作者您好，您在论文“The detailed running instructions and orchestration scripts”中所做的工作非常精彩，也非常感谢您的开源分享！
如果您方便的话，我想请问下您能否提供**详细的运行说明和编排脚本**呢，我的邮箱是282281397@qq.com？谢谢您~

另外，想请教您一个小问题，您在论文5.1部分提到了“We follow Lin et al.(2020)”，为什么Role types是22种呢，在网上查到的统计数据中，ACE 2005共有35种 argument role。这个小问题我不太明白（也有可能在您的实验代码中将会体现，因此我也十分期待复现您的实验呢~），如果您方便的话请解答一下~感谢作者大大~

**Comment by wanmok** [comment]
Replied in email.
